export interface Card {
  id: number;
  name: string;
  description: string;
  power: number;
  element: string;
  type: string;
}

export const cards: Card[] = [
  {
    id: 1,
    name: "Water Dragon",
    description: "A majestic dragon that commands the flow of rivers.",
    power: 9,
    element: "Water",
    type: "Unit",
  },
  {
    id: 2,
    name: "Water Guardian",
    description: "A protective spirit of serene water realms.",
    power: 7,
    element: "Water",
    type: "Unit",
  },
  {
    id: 3,
    name: "Water Sprite",
    description: "A playful sprite that controls water flows.",
    power: 4,
    element: "Water",
    type: "Unit",
  },
  {
    id: 4,
    name: "Tidal Eruptor",
    description: "A spell to summon mighty tidal waves.",
    power: 6,
    element: "Water",
    type: "Spell",
  },
  {
    id: 5,
    name: "Iceberg Giant",
    description: "A giant formed from ancient glaciers.",
    power: 8,
    element: "Water",
    type: "Unit",
  },
  {
    id: 6,
    name: "Aqua Shield",
    description: "A protective shield made of water.",
    power: 3,
    element: "Water",
    type: "Effect",
  },
  {
    id: 7,
    name: "Torrential Flow",
    description: "A devastating flow of water, drowning foes in its path.",
    power: 9,
    element: "Water",
    type: "Effect",
  },
  {
    id: 8,
    name: "Glacier Wall",
    description: "An impenetrable wall of ice, born from frigid waters.",
    power: 5,
    element: "Water",
    type: "Effect",
  },
  {
    id: 9,
    name: "Hydro Blast",
    description: "A powerful blast of water that sweeps away everything.",
    power: 6,
    element: "Water",
    type: "Spell",
  },
  {
    id: 10,
    name: "Mystic Leviathan",
    description: "A mythical creature that rises from the ocean depths.",
    power: 9,
    element: "Water",
    type: "Unit",
  },
  {
    id: 11,
    name: "Frost Sorcerer",
    description: "A sorcerer who manipulates ice and frost with ease.",
    power: 7,
    element: "Water",
    type: "Unit",
  },
  {
    id: 12,
    name: "River Spirit",
    description: "A spirit that commands the river currents.",
    power: 5,
    element: "Water",
    type: "Unit",
  },  {
    id: 13,
    name: "Inferno Dragon",
    description: "A dragon born from the heart of a volcano, breathing flames that scorch the battlefield.",
    power: 9,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 14,
    name: "Blaze Knight",
    description: "A knight whose armor is forged in dragon flame, unyielding in the face of danger.",
    power: 7,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 15,
    name: "Pyro Mage",
    description: "A master of fire magic, capable of casting devastating firestorms.",
    power: 6,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 16,
    name: "Flame Whip",
    description: "A spell that conjures a whip of fire, lashing out at multiple enemies at once.",
    power: 5,
    element: "Fire",
    type: "Spell",
  },
  {
    id: 17,
    name: "Firewall",
    description: "A defensive spell that creates a wall of fire, protecting allies from harm.",
    power: 4,
    element: "Fire",
    type: "Effect",
  },
  {
    id: 18,
    name: "Burning Phoenix",
    description: "A mythical bird that combusts into flames when struck, only to rise again.",
    power: 8,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 19,
    name: "Volcano Eruption",
    description: "An effect that simulates a volcanic eruption, dealing massive area damage.",
    power: 9,
    element: "Fire",
    type: "Effect",
  },
  {
    id: 20,
    name: "Ember Spirit",
    description: "A spirit that embodies the flickering flames of a dying fire, capable of rapid regeneration.",
    power: 4,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 21,
    name: "Lava Golem",
    description: "A golem made of molten lava, its touch burns and its presence warms.",
    power: 7,
    element: "Fire",
    type: "Unit",
  },
  {
    id: 22,
    name: "Scorching Rays",
    description: "A spell that sends forth scorching rays of sun, piercing through defenses.",
    power: 5,
    element: "Fire",
    type: "Spell",
  },
  {
    id: 23,
    name: "Hellfire Blast",
    description: "A blast of hellfire that engulfs enemies, leaving nothing but ashes.",
    power: 8,
    element: "Fire",
    type: "Spell",
  },
  {
    id: 24,
    name: "Charred Warrior",
    description: "A warrior whose battles have left him charred, yet his fighting spirit burns fiercer than ever.",
    power: 6,
    element: "Fire",
    type: "Unit",
  },
];

